all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  children:
    prod:
      hosts:
        my-server:
          ansible_host: ivan-arturo.grandi-flores.takima.cloud