- name: Run HTTPD
  docker_container:
    name: httpd
    image: alik265/tp-devops-httpd:latest
    pull: true
    networks:
      - name: app-proxy-network

    ports:
      - "80:80"
    restart_policy: no