name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [main]
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: TP1/spring-app
      - name : Use Sonar cloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=AlikBook_Docker-TPs-Ivan-Grandi -Dsonar.organization=alikbook -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file TP1/spring-app/pom.xml
        